#!/bin/bash
set -e

wget -q -O openrefine-2.8.tar.gz https://github.com/OpenRefine/OpenRefine/releases/download/2.8/openrefine-linux-2.8.tar.gz
mkdir -p $HOME/.openrefine
tar xzf openrefine-2.8.tar.gz -C $HOME/.openrefine
rm openrefine-2.8.tar.gz

mkdir -p $HOME/openrefine

TOMCAT_REL="9"
TOMCAT_VERSION="9.0.52"

wget https://archive.apache.org/dist/tomcat/tomcat-${TOMCAT_REL}/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz -P $HOME
tar -xf $HOME/apache-tomcat-${TOMCAT_VERSION}.tar.gz -C $HOME/
mv $HOME/apache-tomcat-${TOMCAT_VERSION} $HOME/tomcat
chmod +x $HOME/.tomcat/bin/*.sh
