#!/bin/bash
set -e

TOMCAT_REL="9"
TOMCAT_VERSION="9.0.52"

wget https://archive.apache.org/dist/tomcat/tomcat-${TOMCAT_REL}/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz -P $HOME
tar -xf $HOME/apache-tomcat-${TOMCAT_VERSION}.tar.gz -C $HOME/
mv $HOME/apache-tomcat-${TOMCAT_VERSION} $HOME/.tomcat
chmod +x $HOME/.tomcat/bin/*.sh

GUACAMOLE_VERSION="1.3.0"
mkdir -p $HOME/.guacamole
mv $HOME/.tomcat/webapps $HOME/.tomcat/webapps.dist
wget "https://apache.mirror.digitalpacific.com.au/guacamole/${GUACAMOLE_VERSION}/binary/guacamole-1.3.0.war" -O $HOME/.tomcat/webapps/ROOT.war
wget "https://apache.mirror.digitalpacific.com.au/guacamole/${GUACAMOLE_VERSION}/source/guacamole-server-1.3.0.tar.gz" -O $HOME/.guacamole/guacamole-server-${GUACAMOLE_VERSION}.tar.gz
tar xvf $HOME/.guacamole/guacamole-server-${GUACAMOLE_VERSION}.tar.gz
cd $HOME/.guacamole/guacamole-server-${GUACAMOLE_VERSION}
./configure --with-init-dir=/etc/init.d
make
make install
ldconfig
rm -r $HOME/.guacamole/guacamole-server-${GUACAMOLE_VERSION}*
